name: Installation et déploiement pour Debian

on:
  push:
    branches:
      - main

jobs:
  test-ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Chargement de la clé SSH privée ...
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: |
            ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Mise à jour de Debian ...
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.SERVER_IP }} "apt update -y"

      - name: Installation de Git ...
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.SERVER_IP }} "apt install git -y"

      - name: Vérifier si le repository est déjà cloné sinon mettre à jour
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.SERVER_IP }} "
            if [ ! -d /home/debian/Ansible ]; then
              git clone https://github.com/Nestea29950/Ansible.git /home/debian/Ansible;
            else
              cd /home/debian/Ansible && git pull;
            fi
          "
          
      - name: Installation d'Ansible ...
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.SERVER_IP }} "
            apt install -y software-properties-common &&
            add-apt-repository --yes --update ppa:ansible/ansible &&
            apt install -y ansible
          "

      - name: Exécution du playbook Ansible ...
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.SERVER_IP }} "
            cd /home/debian/Ansible && ansible-playbook -i inventory.ini playbook.yml
          "


