---
- name: Créer un répertoire sur la machine distante
  hosts: webservers  # Utilise le groupe défini dans votre fichier hosts.ini
  become: yes         # Utilisation des privilèges administrateur (sudo)
  tasks:
    - name: Créer le répertoire /home/debian/test
      file:
        path: /home/debian/test
        state: directory
        mode: '0755'
