- name: Installer Docker et Docker Compose
  hosts: webservers
  become: yes
  tasks:
    - name: Cloner le repository Git contenant le fichier docker-compose.yml
      git:
        repo: 'https://github.com/Nestea29950/Ansible.git'
        dest: '/home/debian/Ansible'
        version: 'main'

    - name: Installer les prérequis pour Docker
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
        update_cache: yes

    - name: Ajouter la clé GPG officielle de Docker
      shell: curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -

    - name: Ajouter le repository Docker pour Debian
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/debian bullseye stable"  # Utilisez la version appropriée de Debian (bullseye, buster, etc.)
        state: present

    - name: Installer Docker
      apt:
        name: docker-ce
        state: latest
        update_cache: yes

    - name: Télécharger et installer Docker Compose
      shell: |
        curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose

    - name: Lancer Docker Compose
      command: docker compose -f /home/debian/Ansible/docker-compose.yml up -d
      args:
        chdir: /home/debian/Ansible