---
- name: Cloner le repository Git contenant le fichier docker-compose.yml
      git:
        repo: 'https://github.com/Nestea29950/Ansible.git'
        dest: '/home/debian/Ansible'
        version: 'main' 